server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

spring:
  application:
    name: consumer-ribbon